<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="css/style.css">
    <title>Login Nsll</title>
</head>
<body>
    <head>
        <!-- espacio para el header de la pagina -->
    </head>
    <section>
        <div>
            <h1 class="titulo">Hola Mundo</h1>
            <div class="fondo">
                <div class="cabeza">
                    <img src="" alt="">
                    <p>Iniciar sesión</p>
                </div>
            </div>
        </div>
    </section>
</body>
</html>